services:
  - type: web
    name: malaria-api
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/MichaelMusembi/linear_regression_model
    branch: main
    dockerfilePath: ./Dockerfile
    rootDir: .
    envVars:
      - key: PORT
        value: 8000
